name: puzzleon_api

services:
  db:
    image: postgres:17.4-alpine3.21
    restart: always
    command: ['postgres', '-c', 'log_statement=all']
    volumes:
      - puzzleon_api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  puzzleon_api:
